import express from 'express';
import { authenticateAccessToken, authenticateCsrfToken } from '../middlewares/index.js';
import { studentRoutes } from '../modules/students/sudent-router.js';
import { authRoutes } from '../modules/auth/auth-router.js';
import { leaveRoutes } from '../modules/leave/leave-router.js';
import { classRoutes } from '../modules/classes/class-router.js';
import { noticeRoutes } from '../modules/notices/notice-router.js';
import { staffRoutes } from '../modules/staff/staff-router.js';
import { accountRoutes } from '../modules/account/account-router.js';
import { departmentRoutes } from '../modules/departments/department-router.js';
import { permissionRoutes } from '../modules/permissions/permission-router.js';
import { attendanceRoutes } from '../modules/attendance/attendance-router.js';
import { subjectRoutes } from '../modules/subjects/subject-router.js';
import { examRoutes } from '../modules/exams/exam-router.js';
import { invoiceRoutes } from '../modules/invoices/invoice-router.js';
import { depositRoutes } from '../modules/deposit/deposit-router.js';
import { feeRoutes } from '../modules/fees/fee-router.js';
import { schoolRoutes } from '../modules/schools/school-router.js';
import { academicLevelRoutes } from '../modules/academic-levels/level-router.js';
import { academicYearRoutes } from '../modules/academic-years/academic-year-router.js';
import { fiscalYearRoutes } from '../modules/fiscal-years/fy-router.js';
import { roleRoutes } from '../modules/roles/role-router.js';
import { paymentRoutes } from '../modules/payments/payment-router.js';
import { miscRoutes } from '../modules/misc/misc.route.js';
import { systemAccessRoutes } from '../modules/system-access/system-access-router.js';
import { classTeacherRoute } from '../modules/class-teachers/class-teachers.route.js';

const router = express.Router();

router.use('', miscRoutes);
router.use('/permissions', authenticateAccessToken, authenticateCsrfToken, permissionRoutes);
router.use('/schools', authenticateAccessToken, authenticateCsrfToken, schoolRoutes);
router.use('/auth', authRoutes);
router.use('/account', authenticateAccessToken, authenticateCsrfToken, accountRoutes);
router.use('/leaves', authenticateAccessToken, authenticateCsrfToken, leaveRoutes);
router.use('/classes', authenticateAccessToken, authenticateCsrfToken, classRoutes);
router.use('/class-teachers', authenticateAccessToken, authenticateCsrfToken, classTeacherRoute);
router.use('/students', authenticateAccessToken, authenticateCsrfToken, studentRoutes);
router.use('/notices', authenticateAccessToken, authenticateCsrfToken, noticeRoutes);
router.use('/staff', authenticateAccessToken, authenticateCsrfToken, staffRoutes);
router.use('/departments', authenticateAccessToken, authenticateCsrfToken, departmentRoutes);
router.use('/roles', authenticateAccessToken, authenticateCsrfToken, roleRoutes);
router.use('/academic/years', authenticateAccessToken, authenticateCsrfToken, academicYearRoutes);
router.use('/fiscal-years', authenticateAccessToken, authenticateCsrfToken, fiscalYearRoutes);
router.use('/attendances', authenticateAccessToken, authenticateCsrfToken, attendanceRoutes);
router.use('/subjects', authenticateAccessToken, authenticateCsrfToken, subjectRoutes);
router.use('/exams', authenticateAccessToken, authenticateCsrfToken, examRoutes);
router.use('/invoices', authenticateAccessToken, authenticateCsrfToken, invoiceRoutes);
router.use('/deposits', authenticateAccessToken, authenticateCsrfToken, depositRoutes);
router.use('/fees', authenticateAccessToken, authenticateCsrfToken, feeRoutes);
router.use('/payments', authenticateAccessToken, authenticateCsrfToken, paymentRoutes);
router.use('/academic/levels', authenticateAccessToken, authenticateCsrfToken, academicLevelRoutes);
router.use('/system-access', systemAccessRoutes);

export { router as v1Routes };
